owner: MerginMaps
repo: status

sites:
  - name: Main Website
    url: https://merginmaps.com
  - name: Translated Website
    url: https://fr.merginmaps.com
  - name: Dashboard and API
    url: https://app.merginmaps.com/ping
  - name: Docs
    url: https://www.merginmaps.com/docs

status-website:
  cname: status.merginmaps.com
  logoUrl: https://raw.githubusercontent.com/merginmaps/status/master/assets/MM_logo_EMBLEM_COLOR_POZ.svg
  name: Mergin Maps System Status
  introTitle: "**Mergin Maps** ecosystem system status page"
  introMessage: For more information check community [Slack chat](https://www.merginmaps.com/community/join) and [Twitter](https://twitter.com/MerginMaps). You can contact [Support](https://support.merginmaps.com/support/tickets/new) for specific issues not already reported as incidents.
  themeUrl: https://status.merginmaps.com/mmtheme.css
  css: "body { font-family: Inter,sans-serif !important; }"
  navbar:
    - title: Use Slack Chat
      href: https://www.merginmaps.com/community/join
    - title: Contact Support
      href: https://support.merginmaps.com/support/tickets/new
    - title: See Twitter
      href: https://twitter.com/MerginMaps
