owner: MerginMaps
repo: status

sites:
  - name: Main Website
    url: https://merginmaps.com/?utm_source=mmsystemstatus
  - name: Translated Website
    url: https://fr.merginmaps.com/?utm_source=mmsystemstatus
  - name: Dashboard and API
    url: https://app.merginmaps.com/ping?utm_source=mmsystemstatus
  - name: Docs
    url: https://www.merginmaps.com/docs/?utm_source=mmsystemstatus

status-website:
  cname: status.merginmaps.com
  logoUrl: https://raw.githubusercontent.com/merginmaps/status/master/assets/MM_logo_EMBLEM_COLOR_POZ.svg
  name: Mergin Maps System Status
  favicon: https://raw.githubusercontent.com/merginmaps/status/master/assets/favicon.ico
  introTitle: "**Mergin Maps** ecosystem system status page"
  introMessage: For more information check community [Slack chat](https://www.merginmaps.com/community/join) and [Twitter](https://twitter.com/MerginMaps). You can contact [Support](https://support.merginmaps.com/support/tickets/new) for specific issues not already reported as incidents.
  theme: light
  customHeadHtml: "<link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'>"
  css: "* {font-family: Inter!important;} :root {--body-background-color: #ffffff; --nav-background-color: #ffffff;     --nav-border-bottom-color: #00a884; --nav-current-border-bottom-color: #00a884; --up-border-left-color: #00a884; }"
  navbar:
    - title: Use Slack Chat
      href: https://www.merginmaps.com/community/join
    - title: Contact Support
      href: https://support.merginmaps.com/support/tickets/new
    - title: See Twitter
      href: https://twitter.com/MerginMaps
